[package]
name = "abnf_to_pest"
version = "0.1.0"
authors = ["Nadrieril <nadrieril@users.noreply.github.com>"]
license = "BSD-2-Clause"
edition = "2018"

[lib]
doctest = false

[dependencies]
abnf = { git = "https://github.com/Nadrieril/abnf" }
itertools = "0.8.0"
pretty = "0.5.2"
