language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - nightly-2019-03-15

install:
- cargo build --release --all --all-features
- cargo tarpaulin --version || RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin

script:
- cargo tarpaulin -v --release --all-features --all --exclude-files dhall_generator/* --exclude-files abnf_to_pest/* --out Xml

after_success: |
  bash <(curl -s https://codecov.io/bash)

