language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - nightly-2019-03-15

before_cache: |
  RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin

install:
- cargo build --release --all --all-features

script:
- cargo test --release --all --all-features

after_success: |
  cargo tarpaulin --release --all --all-features --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

