[package]
name = "dhall"
version = "0.1.0"
authors = ["NanoTech <nanotech@nanotechcorp.net>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
lalrpop = "0.16.3"

[dependencies]
bytecount = "0.5.1"
lalrpop-util = "0.16.3"
nom = "3.0.0"
term-painter = "0.2.3"
