[package]
name = "dhall_proc_macros"
version = "0.1.0"
authors = ["Nadrieril <nadrieril@users.noreply.github.com>"]
license = "BSD-2-Clause"
edition = "2018"

[lib]
proc-macro = true
doctest = false

[dependencies]
itertools = "0.8.0"
quote = "0.6.11"
proc-macro2 = "0.4.27"
syn = "0.15.29"
