[package]
name = "dhall"
version = "0.1.0"
authors = ["NanoTech <nanotech@nanotechcorp.net>", "Nadrieril <nadrieril@users.noreply.github.com>"]
license = "BSD-2-Clause"
edition = "2018"
build = "build.rs"

[features]
nothreads = [] # disable threads for tarpaulin

[dependencies]
bytecount = "0.5.1"
itertools = "0.8.0"
term-painter = "0.2.3"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.9.0"
dhall_core = { path = "../dhall_core" }
dhall_generator = { path = "../dhall_generator" }

[dev-dependencies]
pretty_assertions = "0.6.1"

[build-dependencies]
walkdir = "2"

